# Generated by Django 5.1.7 on 2025-04-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_appointmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
