# Generated by Django 5.2 on 2025-04-25 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_views_recipe_cost_recipe_cost_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_1_response',
            field=models.TextField(blank=True, help_text='How is your current diet?', null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_2_response',
            field=models.TextField(blank=True, help_text='Any allergies or restrictions?', null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_3_response',
            field=models.TextField(blank=True, help_text='Are you open to recipe substitutions?', null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
