# Generated by Django 5.2 on 2025-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_appointmenthistory_question_1_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_4_response',
            field=models.TextField(blank=True, help_text='Is this your 1st time meeting with a Doctor about diet?', null=True),
        ),
    ]
