# Generated by Django 5.2 on 2025-04-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_appointmenthistory_question_4_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_5_response',
            field=models.TextField(blank=True, help_text='How active are you during the week? (sedentary, lightly active, very active)', null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_6_response',
            field=models.TextField(blank=True, help_text='What are your current health or diet goals? (e.g., weight loss, muscle gain, healthier eating)', null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_7_response',
            field=models.TextField(blank=True, help_text='How many meals do you typically eat in a day?', null=True),
        ),
        migrations.AddField(
            model_name='appointmenthistory',
            name='question_8_response',
            field=models.TextField(blank=True, help_text='Have you been diagnosed with any medical conditions that affect your diet? (e.g., diabetes, hypertension)', null=True),
        ),
        migrations.AlterField(
            model_name='appointmenthistory',
            name='question_1_response',
            field=models.TextField(blank=True, help_text='Do you follow any specific diet? (e.g., vegetarian, keto, gluten-free)', null=True),
        ),
        migrations.AlterField(
            model_name='appointmenthistory',
            name='question_4_response',
            field=models.TextField(blank=True, help_text='Are you currently taking any medication that affects your appetite or digestion?', null=True),
        ),
    ]
