# Generated by Django 5.2 on 2025-04-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
